server:
  port: 8081
spring:
  application:
    name: myBlog
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: Agni5403#
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL version